###
PUT http://localhost:8888/.netlify/functions/build_matches?eventId=6578ad76e53c8b23971032c4&divisionId=6578a6dae53c8b23971032c1

###
PUT http://localhost:8888/.netlify/functions/build_matches?eventId=6578ad76e53c8b23971032c4&divisionId=6578a6dae53c8b23971032c2


###
GET http://localhost:8888/.netlify/functions/build_matches?eventId=66958096492636e283f83f4c&divisionId=00000000492636e283f83f4d&players=1




###
DELETE  http://localhost:8888/.netlify/functions/time-records?timeRecordId=657a8a8bddc6eed7f0384521

###
POST http://localhost:8888/.netlify/functions/time-records HTTP/1.1
content-type: application/json

  {
    "shooterId": "6578d331e53c8b23971032cf",
    "divisionId": "6578a6dae53c8b23971032c1",
    "sTime": 4.10,
    "penalties": 0
  }


###
GET http://localhost:8888/.netlify/functions/time-records?shooterId=6578d331e53c8b23971032c5&divisionId=6578a6dae53c8b23971032c1

###
GET http://localhost:8888/.netlify/functions/events


###
GET https://localhost:8888/.netlify/functions/events?split_duels=1&order=1&date_from=2024-01-01"

####
GET http://localhost:8888/.netlify/functions/events?event_id=661ab4f9c412f4a5f17f0624

###
GET http://localhost:8888/.netlify/functions/events?split_duels=1&order=1&date_from=2024-01-01&date_to=2024-05-01"

###
GET http://localhost:8888/.netlify/functions/events?split_duels=1&order=1&date_from=2023-01-01&date_to=2025-05-01&event_id=661ab4f9c412f4a5f17f0624

###
GET http://localhost:8888/.netlify/functions/events?split_duels=1&event_id=6621d68dc55df3c3e277cc32

###
GET http://localhost:8888/.netlify/functions/time-records?shooterId=6578d331e53c8b23971032c5&divisionId=6578a6dae53c8b23971032c1&shooterDivisionId=2332434

###
GET http://localhost:8888/.netlify/functions/time-records?rank=2

###
GET http://localhost:8888/.netlify/functions/time-records?eventId=661ab4f9c412f4a5f17f0624&report=1

###
GET http://localhost:8888/.netlify/functions/shooters_divisions?eventId=661ab4f9c412f4a5f17f0624

###
GET http://localhost:8888/.netlify/functions/guns

###
GET http://localhost:8888/.netlify/functions/range?rangeId=66bb69bb55b6d11c7ed7a613


###  &divisionId=000000006018d78882298a4c&category=5
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=6667413bc1a9d669a8b4d7a2



###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=6634cb8eca4cc35cc2bbed37
###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=6640c844109c47cb34890fae
###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=6667413bc1a9d669a8b4d7a2
###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=66702937628fd8e349840a0a
###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=6670db0f75a075d179f41097
###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=664e66ddfcfb516b8696925e
###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=6681e5bce9cc6ac4c9e16d56
###
PATCH http://localhost:8888/.netlify/functions/duel_results?eventId=66958096492636e283f83f4c





####
PATCH http://tpmonline.com.br/.netlify/functions/duel_results?eventId=66958096492636e283f83f4c&divisionId=00000000492636e283f83f4

####
GET http://localhost:8888/.netlify/functions/duel_results?eventId=66958096492636e283f83f4c&divisionId=00000000492636e283f83f4d&category=5




#####
GET http://localhost:8888/.netlify/functions/duel_results?shooterA=6699af6d945fc3e02a61fa7c&shooterB=66999521c320bcf6e804e260&divisioName=Pistola

# /.netlify/functions/duel_results?shooterA=661ab6ae501fc2cd2ff558e1&shooterB=661be2184277ae7378717fe3&divisioName=Pistola





###
GET http://localhost:8888/.netlify/functions/shooters_divisions_v2?eventId=661ab4f9c412f4a5f17f0624

####>>
GET http://localhost:8888/.netlify/functions/shooters_divisions?eventId=6578ad76e53c8b23971032c4&email=petra@tpm.com

#### Issue
GET http://localhost:8888/.netlify/functions/shooters_divisions_v2?eventId=6621d68dc55df3c3e277cc32&email=rodrigo.manso@gmail.com

####>>
GET http://localhost:8888/.netlify/functions/shooters_divisions_v2?eventId=6578ad76e53c8b23971032c4&email=petra@tpm.com


####>>>>>>> abd5c50f5e922207c4aaf32b8c11e5e167d03d5d
GET https://tpmonline.netlify.app/.netlify/functions/shooters_divisions?eventId=6578ad76e53c8b23971032c4


###
GET http://localhost:8888/.netlify/functions/divisions

###
GET http://localhost:8888/.netlify/functions/eventconfig?eventId=6578ad76e53c8b23971032c4

###
GET http://localhost:8888/.netlify/functions/eventconfig?eventId=65adcf12c90395b92fb7e7b8

###
http://localhost:8888 

###
GET http://localhost:8888/.netlify/functions/shooters?logged

###
GET http://localhost:8888/.netlify/functions/records?eventID=1&shooterID=1&divisionID=2
