DELETE  http://localhost:8888/.netlify/functions/time-records?timeRecordId=657a8a8bddc6eed7f0384521

###
POST http://localhost:8888/.netlify/functions/time-records HTTP/1.1
content-type: application/json

  {
    "shooterId": "6578d331e53c8b23971032cf",
    "divisionId": "6578a6dae53c8b23971032c1",
    "sTime": 4.10,
    "penalties": 0
  }


###

GET http://localhost:8888/.netlify/functions/time-records?shooterId=6578d331e53c8b23971032c5&divisionId=6578a6dae53c8b23971032c1

###

GET http://localhost:8888/.netlify/functions/shooters_divisions?eventId=6578ad76e53c8b23971032c4

###

GET http://localhost:8888/.netlify/functions/divisions

###
GET http://localhost:8888/.netlify/functions/eventconfig?eventId=6578ad76e53c8b23971032c4

###
http://localhost:8888 

###
GET http://localhost:8888/.netlify/functions/shooters?eventID=1&divisionID=1

###
GET http://localhost:8888/.netlify/functions/records?eventID=1&shooterID=1&divisionID=2
